blank_issues_enabled: true
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/orgs/cloudsnacks/discussions
    about: Ask questions and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/cloudsnacks
    about: Check our documentation for guides and references
